### ISSUE TITLE
What is our CSS Framework/Library?

### ISSUE THREAD

**Issue by mhassany** [mhassany/sit-690#20]
@vaityshrey @BenjiTheC which css library do you choose as the base for your css styles?

**Comment by BenjiTheC** [comment]
Let's use Bootstrap since I've been using it from last semester and have gained some experience with customizing it from sass source files recently

**Comment by mhassany** [comment]
What is the size of bootstrap gziped?

**Comment by mhassany** [comment]
That is a good choice, @Svaity what do you think?

**Comment by vaityshrey** [comment]
Bootstrap seems like a good choice

**Comment by BenjiTheC** [comment]
Since we switch to React, I'm proposing the change of component framework to `material-ui`.

The [`material-ui`](https://material-ui.com) is the React UI framework developed and open sourced by Google. 

The reason I choose `material-ui` over `react-bootstrap` is because the `material-ui` is more sophisticated as a **React UI framework** than `react-bootstrap`. `react-bootstrap` was developed from React natively only since Bootstrap 4 components. And the number of stars for `material-ui` repo on GitHub is way larger then `react-bootstrap`'s.

**Comment by mhassany** [comment]
great, material-ui it is.
i am closing this issue since we decided that.
feel free to reopen it if it is necessary.
